version: "3.7"
services:
  www:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public/:/var/www/html
      - ./:/var/www
    depends_on:
      - database

  database:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: textMe
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: "3306"
    ports:
      - "8081:80"
    depends_on:
      - database

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeMe!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeMe!"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - 8001:80

volumes:
  mercure_data:
  mercure_config:
