version: "3.7"
services:
  php:
    container_name: php
    image: php
    depends_on:
      - database
      - mercure
    restart: unless-stopped
    environment:
      APP_ENV: dev
      MERCURE_PUBLISH_URL: http://mercure/.well-known/mercure
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dev

  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "8000:80"
    networks:
      - dev

  database:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - dev

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeMe!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeMe!"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - 8001:80

networks:
  dev:

volumes:
  mercure_data:
  mercure_config:
